In [114]:
#create a array using numpy

import numpy as np
a=[1,2,3,4]
b=np.array(a)
b

array([1, 2, 3, 4])

In [113]:
#create a array using numpy 2nd method
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [70]:
#create an array of 10 random integer

a=np.random.randint(1,100,10)
a

array([47, 67, 29, 63, 58, 17, 22, 40, 84, 90])

In [72]:
#create an array which contains elements between 10-20

a=np.random.randint(10,20,10)
a

array([10, 14, 12, 13, 18, 13, 14, 19, 19, 14])

In [87]:
#create a array which contains 5 ..10 times

a=np.random.randint(5,6,10)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [93]:
#create one dimensional array and convert it into 3X3 matrix

a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
#create a 2d array of size of 3X3 matrix but all elements must be o-1
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [116]:
#2nd method
a=np.random.randint(0,2,9).reshape(3,3)
a

array([[0, 0, 1],
       [1, 0, 1],
       [0, 0, 0]])

In [98]:
#3rd method
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
#4th method
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
#concatenate 2d array both horizontally and vertically

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[0,9,8],[7,6,5]])

In [105]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
b

array([[0, 9, 8],
       [7, 6, 5]])

In [108]:
np.hstack([a,b]) #horizontally

array([[1, 2, 3, 0, 9, 8],
       [4, 5, 6, 7, 6, 5]])

In [109]:
np.vstack([a,b]) #vertically

array([[1, 2, 3],
       [4, 5, 6],
       [0, 9, 8],
       [7, 6, 5]])