In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:\\Users\\YASH\\OneDrive\\Desktop\\ty\\covid_toy.csv")

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df=df.dropna()

In [6]:
df=df.drop(columns=['age','fever'])

In [7]:
df.head()

gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
df.shape

(90, 4)

# get_dummies method

In [11]:
p=pd.get_dummies(df,columns=['gender','cough','city','has_covid'])

In [13]:
p.shape

(90, 10)

In [14]:
p

gender_Female  gender_Male  cough_Mild  cough_Strong  city_Bangalore  \
0           False         True        True         False           False   
1           False         True        True         False           False   
2           False         True        True         False           False   
3            True        False        True         False           False   
4            True        False        True         False           False   
..            ...          ...         ...           ...             ...   
95           True        False        True         False            True   
96           True        False       False          True           False   
97           True        False        True         False            True   
98           True        False       False          True           False   
99           True        False       False          True           False   

    city_Delhi  city_Kolkata  city_Mumbai  has_covid_No  has_covid_Yes  
0        False          True        False          True          False  
1         True         False        False         False           True  
2         True         False        False          True          False  
3        False          True        False          True          False  
4        False         False         True          True          False  
..         ...           ...          ...           ...            ...  
95       False         False        False          True          False  
96       False          True        False         False           True  
97       False         False        False          True          False  
98       False         False         True          True          False  
99       False          True        False         False           True  

[90 rows x 10 columns]

In [15]:
p=pd.get_dummies(df,columns=['gender','cough','city','has_covid'],drop_first=True)

In [16]:
p.shape

(90, 6)

In [17]:
ohe=OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

In [21]:
df_new=ohe.fit_transform(df[['gender','cough','city','has_covid']])

D:\andaconda\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [22]:
df_new.shape

(90, 6)

# column transformer

In [25]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import OrdinalEncoder

In [26]:
df=pd.read_csv("C:\\Users\\YASH\\OneDrive\\Desktop\\ty\\covid_toy.csv")

In [27]:
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [28]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [32]:
x_train

age  gender  fever   cough       city
70   68  Female  101.0  Strong      Delhi
33   26  Female   98.0    Mild    Kolkata
12   25  Female   99.0  Strong    Kolkata
46   19  Female  101.0    Mild     Mumbai
29   34  Female    NaN  Strong     Mumbai
..  ...     ...    ...     ...        ...
73   34    Male   98.0  Strong    Kolkata
35   82  Female  102.0  Strong  Bangalore
31   83    Male  103.0    Mild    Kolkata
44   20    Male  102.0  Strong      Delhi
41   82    Male    NaN    Mild    Kolkata

[80 rows x 5 columns]

# Manually Type Output

In [34]:
# adding simple imputer to fever column
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[['fever']])

#also the test data
x_test_fever=si.fit_transform(x_test[['fever']])
x_train_fever.shape

(80, 1)

In [35]:
#Ordinal Encoding --> Cough

oe=OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough=oe.fit_transform(x_train[['cough']])

#also the test data
s_test_cough=oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [37]:
# OneHotEncoding -->Gender,city

ohe=OneHotEncoder(drop='first',sparse=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])

#also the test data
x_test_gender_city=ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

D:\andaconda\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
D:\andaconda\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 4)

In [38]:
#Extracting age

x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values

#also the test data

x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

In [39]:
x_train_age.shape

(80, 1)

In [40]:
x_train_transform=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)

In [41]:
x_train_transform.shape

(80, 7)

# by the help of column transformer

In [42]:
from sklearn.compose import ColumnTransformer  #this is how to import ColumnTransformer

transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']), #in a 'fever' column by the help of Si we will fill missing values
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']), #by this process we encode our
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough') #remainder =passthrough==>it means rest all the columns remnain same

In [43]:
transformer.fit_transform(x_train).shape

D:\andaconda\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 7)

In [45]:
transformer.transform(x_test).shape

(20, 7)

# Function TRansformer

In [1]:
#we can pass our costom conditon on an array

In [2]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [4]:
#create a datbase
X=np.array([[1,2],[3,4]])

In [5]:
#define the transformation fun
log_transform=FunctionTransformer(np.log1p)

In [6]:
#define the transformer to the dataset
X_transformed=log_transform.transform(X)

In [7]:
#view the transform data
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [8]:
#eg 2
def my_feature_engineering(X):
    return np.hstack((X,X**2))

In [9]:
#create a FunctionTransformer to apply the current fun
custom_transformer= FunctionTransformer(my_feature_engineering)

In [10]:
#apply the transformer to the input data
X_transformed =custom_transformer.transform(X)

In [11]:
#view
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [12]:
#eg 3
def my_scaling(X):
    return X/np.max(X)

In [13]:
#create a FunctionTransformer to apply the current fun
custom_transformer= FunctionTransformer(my_scaling)

In [14]:
#apply the transformer to the input data
X_transformed =custom_transformer.transform(X)

In [15]:
#view
print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [16]:
#eg4
X=np.array ([[1,2],[3,np.nan]])
def my_cleaning(X):
    X[np.isnan(X)]=0
    return X

In [17]:
#create a FunctionTransformer to apply the current fun
custom_transformer= FunctionTransformer(my_cleaning)

In [18]:
#apply the transformer to the input data
X_transformed =custom_transformer.transform(X)

In [19]:
#view
print(X_transformed)

[[1. 2.]
 [3. 0.]]
